-- Витрины: звёздная схема для продаж и остатков.
--
-- Измерение товара нормализовано в «снежинку» (товар -> подкатегория ->
-- категория -> группа): иерархию правят категорийные менеджеры, и держать её
-- в одном месте дешевле, чем обновлять тысячи строк товаров. Для BI поверх
-- снежинки есть плоское представление v_product.
--
-- Суррогатные ключи -1 и -2 зарезервированы:
--   -1  неизвестно / не применимо (анонимная покупка, товара нет в каталоге)
--   -2  ссылка есть, но в источнике записи нет (клиент из заказа не найден в CRM)

CREATE SCHEMA IF NOT EXISTS marts;

-- ------------------------------------------------------------------ даты
CREATE TABLE marts.dim_date (
    date_key      integer PRIMARY KEY,  -- 20260930
    date          date    NOT NULL UNIQUE,
    year          smallint NOT NULL,
    quarter       smallint NOT NULL,
    month         smallint NOT NULL,
    month_name    text    NOT NULL,
    iso_week      smallint NOT NULL,
    day_of_week   smallint NOT NULL,  -- 1 = понедельник
    day_name      text    NOT NULL,
    is_weekend    boolean NOT NULL,
    is_holiday    boolean NOT NULL
);

INSERT INTO marts.dim_date
SELECT to_char(d, 'YYYYMMDD')::int,
       d,
       extract(year FROM d),
       extract(quarter FROM d),
       extract(month FROM d),
       (ARRAY['январь','февраль','март','апрель','май','июнь','июль','август',
              'сентябрь','октябрь','ноябрь','декабрь'])[extract(month FROM d)],
       extract(week FROM d),
       extract(isodow FROM d),
       (ARRAY['пн','вт','ср','чт','пт','сб','вс'])[extract(isodow FROM d)],
       extract(isodow FROM d) IN (6, 7),
       -- государственные праздники РК с фиксированной датой
       to_char(d, 'MM-DD') IN ('01-01', '01-02', '03-08', '03-21', '03-22', '03-23', '05-01',
                               '05-07', '05-09', '07-06', '08-30', '10-25', '12-16')
FROM generate_series(date '2020-01-01', date '2030-12-31', interval '1 day') AS g(d);

-- -------------------------------------------------------------- магазины
CREATE TABLE marts.dim_store (
    store_sk    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hk_store    uuid    UNIQUE,
    store_code  text    NOT NULL,
    name        text,
    city        text,
    format      text,
    area_sqm    numeric(7,1),
    opened_on   date,
    closed_on   date,
    updated_at  timestamptz NOT NULL DEFAULT now()
);
INSERT INTO marts.dim_store (store_sk, store_code, name) VALUES (-1, '?', 'Неизвестный магазин');

-- ---------------------------------------------------- товары (снежинка)
CREATE TABLE marts.dim_product_group (
    group_sk    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name  text NOT NULL UNIQUE
);

CREATE TABLE marts.dim_product_category (
    category_sk    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_sk       integer NOT NULL REFERENCES marts.dim_product_group,
    category_name  text    NOT NULL,
    UNIQUE (group_sk, category_name)
);

CREATE TABLE marts.dim_product_subcategory (
    subcategory_sk    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_sk       integer NOT NULL REFERENCES marts.dim_product_category,
    subcategory_name  text    NOT NULL,
    UNIQUE (category_sk, subcategory_name)
);

INSERT INTO marts.dim_product_group (group_sk, group_name) VALUES (-1, 'Без категории');
INSERT INTO marts.dim_product_category (category_sk, group_sk, category_name)
VALUES (-1, -1, 'Без категории');
INSERT INTO marts.dim_product_subcategory (subcategory_sk, category_sk, subcategory_name)
VALUES (-1, -1, 'Без категории');

CREATE TABLE marts.dim_product (
    product_sk         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hk_product         uuid    UNIQUE,
    sku                text    NOT NULL,
    name               text,
    brand              text,
    unit               text,
    status             text,
    subcategory_sk     integer NOT NULL DEFAULT -1 REFERENCES marts.dim_product_subcategory,
    supplier_code      text,
    purchase_currency  text,
    retail_price       numeric(12,2),
    in_catalog         boolean NOT NULL DEFAULT true,
    updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dim_product_subcategory_ix ON marts.dim_product (subcategory_sk);
INSERT INTO marts.dim_product (product_sk, sku, name, in_catalog)
VALUES (-1, '?', 'Неизвестный товар', false);

CREATE VIEW marts.v_product AS
SELECT p.product_sk, p.sku, p.name, p.brand, p.unit, p.status, p.retail_price,
       p.purchase_currency, p.in_catalog,
       s.subcategory_name, c.category_name, g.group_name
FROM marts.dim_product p
JOIN marts.dim_product_subcategory s USING (subcategory_sk)
JOIN marts.dim_product_category c USING (category_sk)
JOIN marts.dim_product_group g USING (group_sk);

-- ------------------------------------------------------- клиенты (SCD2)
-- Персональных данных здесь нет: имя, e-mail и телефон остаются в
-- raw_vault.sat_customer_pii, куда у аналитиков доступа нет.
CREATE TABLE marts.dim_customer (
    customer_sk        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hk_customer        uuid,
    customer_id        text    NOT NULL,
    city               text,
    loyalty_tier       text,
    marketing_consent  boolean,
    gender             text,
    birth_year         integer,
    email_domain       text,
    registered_at      timestamptz,
    is_deleted         boolean NOT NULL DEFAULT false,
    valid_from         timestamptz NOT NULL,
    valid_to           timestamptz NOT NULL,
    is_current         boolean NOT NULL,
    UNIQUE (hk_customer, valid_from)
);
-- поиск версии, действовавшей на момент заказа
CREATE INDEX dim_customer_asof_ix ON marts.dim_customer (hk_customer, valid_from, valid_to);
CREATE UNIQUE INDEX dim_customer_current_ix ON marts.dim_customer (hk_customer) WHERE is_current;
INSERT INTO marts.dim_customer (customer_sk, customer_id, valid_from, valid_to, is_current)
VALUES (-1, 'анонимный покупатель', '-infinity', 'infinity', true),
       (-2, 'нет в CRM', '-infinity', 'infinity', true);

-- -------------------------------------------------------- факт продаж
-- Зерно: строка заказа. Номер заказа и строки — вырожденное измерение.
-- Секционирование по месяцам: отчёты почти всегда режут по периоду, а
-- пересборка месяца сводится к работе с одной секцией.
CREATE TABLE marts.fact_sales (
    date_key           integer NOT NULL REFERENCES marts.dim_date,
    order_no           text    NOT NULL,
    line_no            integer NOT NULL,
    order_ts           timestamptz NOT NULL,
    store_sk           integer NOT NULL,
    product_sk         integer NOT NULL,
    customer_sk        bigint  NOT NULL,
    hk_customer        uuid,
    channel            text    NOT NULL,
    payment_type       text,
    order_status       text    NOT NULL,
    promo_campaign_id  text,
    qty                numeric(10,3) NOT NULL,
    unit_price         numeric(12,2) NOT NULL,
    gross_amount       numeric(14,2) NOT NULL,
    discount_amount    numeric(14,2) NOT NULL,
    net_amount         numeric(14,2) NOT NULL,  -- 0 для отменённых и возвращённых
    unit_cost_kzt      numeric(14,2),
    cost_amount        numeric(14,2),
    margin_amount      numeric(14,2),
    fx_rate_date       date,
    row_hash           uuid    NOT NULL,
    updated_at         timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (date_key, order_no, line_no)
) PARTITION BY RANGE (date_key);

DO $$
DECLARE m date;
BEGIN
    FOR m IN SELECT generate_series(date '2024-12-01', date '2027-12-01', interval '1 month') LOOP
        EXECUTE format(
            'CREATE TABLE marts.fact_sales_%s PARTITION OF marts.fact_sales FOR VALUES FROM (%s) TO (%s)',
            to_char(m, 'YYYYMM'), to_char(m, 'YYYYMMDD'),
            to_char(m + interval '1 month', 'YYYYMMDD'));
    END LOOP;
END $$;
CREATE TABLE marts.fact_sales_default PARTITION OF marts.fact_sales DEFAULT;

CREATE INDEX fact_sales_store_ix ON marts.fact_sales (store_sk, date_key);
CREATE INDEX fact_sales_product_ix ON marts.fact_sales (product_sk);
CREATE INDEX fact_sales_customer_ix ON marts.fact_sales (hk_customer, order_ts);

-- ------------------------------------------------- факт остатков (снимок)
CREATE TABLE marts.fact_stock_daily (
    date_key     integer NOT NULL REFERENCES marts.dim_date,
    store_sk     integer NOT NULL,
    product_sk   integer NOT NULL,
    qty_on_hand  numeric(12,3) NOT NULL,
    stock_cost   numeric(14,2),
    PRIMARY KEY (date_key, store_sk, product_sk)
);

-- ------------------------------------------------------- RFM-сегменты
CREATE TABLE marts.customer_rfm (
    customer_sk     bigint PRIMARY KEY,
    customer_id     text,
    last_order_date date,
    recency_days    integer,
    orders          integer,
    revenue         numeric(16,2),
    r_score         smallint,
    f_score         smallint,
    m_score         smallint,
    segment         text,
    calculated_at   timestamptz NOT NULL DEFAULT now()
);

-- ------------------------------------------------------- доступ
GRANT USAGE ON SCHEMA marts TO analyst_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA marts TO analyst_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA marts GRANT SELECT ON TABLES TO analyst_ro;
